### PR TITLE
Adds glyphicons to upload and create collection

### PR DESCRIPTION
**Pull request by mtribone**
Brining back some aspects of IconSphere to keep interface elements consistent.

### CODE REVIEW

**Comment by mtribone** [comment]
screen shot 2015-03-06 at 8 50 19 am

**Comment by awead** [comment]
:+1: to merge as soon as Travis is :green_heart:

**Comment by mtribone** [comment]
@awead What do we do for 3 hours while Travis is working? :smirk_cat:

**Comment by mtribone** [comment]
Hrrrm...just found an old thread.https://github.com/projecthydra/sufia/issues/534

Perhaps take @awead advice
https://github.com/awead/catalog/blob/master/config/locales/en.yml#L10

**Comment by awead** [comment]
@mjgiarlo yeah, forgot about that. Take a look at https://github.com/projecthydra/sufia/blob/master/config/locales/sufia.en.yml#L161
and you can put the html right into the yaml.

**Comment by mjgiarlo** [comment]
Travis got sad. :/

**Comment by mjgiarlo** [comment]
(BUT I LOVE THE ICONZ!)

**Comment by awead** [comment]
#952 will fix this. @mtribone you'll need to fetch this from upstream and merge it into psu-stewardship/sufia, rebase, and then force push.

**Comment by mtribone** [comment]
@awead :clap:

**Pull request merged**
