### PR TITLE
Fixes #1487 - Fix intermittent failure to add file to collection

### LINKED ISSUE #1487: Fix error  "uninitialized constant Sufia::GenericFile::Actor::Collection" during upload to collection
A problem was noted that in a Linux environment with Apache and Passenger, sometimes an error would occur when attempting to upload files directly to a collection.  The error:  uninitialized constant Sufia::GenericFile::Actor::Collection.  This is intermittent.  Some uploads will succeed and others will fail.

It is unclear why rails sometimes can find Collection and other times not.  The fix is to more specifically address the Collection class with ::Collection to avoid the prepending of Sufia::GenericFile::Actor.

Additionally, it was noted that apps may have their own FacetsHelper class.  To aid apps to use the facet helpers required for collection faceting, the method for determining whether to show the collection facet was moved to a concern.  This allows apps with there own facet helpers can do a simple include of Sufia::FacetsHelperBehavior in their FacetsHelper class.

### PR DESCRIPTION
**Pull request by elrayle**
* fix error "uninitialized constant Sufia::GenericFile::Actor::Collection"
* move Sufia facet helpers to a concern

### CODE REVIEW

**Comment by mjgiarlo** [comment]
One travis build failed, and it looks like it's related to the recent sprockets-rails 3.0.0 release. That was [already fixed in 6.x-stable](https://github.com/projecthydra/sufia/blob/6.x-stable/lib/sufia.rb#L39-L50), so I'm puzzled why your push was affected by this. Is this rebased on the latest in `6.x-stable`?

**Comment by mjgiarlo** [comment]
Oh, and does this fix #1487? If so, could you add "Fixes #1487" to your commit message so it automatically closes that issue?

**Comment by mjgiarlo** [comment]
(Thanks for the PR, @elrayle!)

**Comment by elrayle** [comment]
Rebased and ready to go.

**Comment by elrayle** [comment]
DO NOT MERGE
Hold off on the merge for this.  I am going to add the solution to the multi-threading locking issue.

**Comment by elrayle** [comment]
Ready to merge

**Comment by mjgiarlo** [comment]
:+1:

@jcoyne @cam156 @awead @hectorcorrea ?

**Pull request merged**
