### PR TITLE
update background workers doc

### PR DESCRIPTION
**Pull request by elrayle**
Please review for accuracy.  Added additional information on message queues in general, resque message queue specifically as used in Sufia, configuration, and validating running processes.

### CODE REVIEW

**Comment by hectorcorrea** [comment]
:+1:

**Comment by jcoyne** [comment]
I'm wondering if we want to continue to be Resque specific. Might someone want to use sidekiq instead?

**Comment by elrayle** [comment]
@jcoyne I think we could definitely expand our documentation more.  If this documentation had existed, it would have saved me a lot of time in debugging.  If someone uses sidekiq and wants to add similar documentation for that, it would be great.

**Comment by mjgiarlo** [comment]
:+1: and I would welcome -- nay, **encourage** -- someone who swapped out Resque for Sidekiq to contribute said documentation back to the project!

**Pull request merged**
