### PR TITLE
Bump curation_concerns to >= 1.0.0.beta1

### PR DESCRIPTION
**Pull request by jcoyne**
@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
There is one failing spec. The terms component seems to now be reporting one more item than actually exists. Can anyone help?
I get 3 results from a search:
http://127.0.0.1:8985/solr/hydra-test/select?q=depositor_ssim:%22user1@example.com%22&fl=id&wt=json&omitHeader=true&facet=false
```json
{"response":{"numFound":3,"start":0,"docs":[{"id":"qr46r082r"},{"id":"dv13zt241"},{"id":"12579s28n"}]},"spellcheck":{"suggestions":[],"correctlySpelled":true}}
```

But 4 from the terms component:
http://127.0.0.1:8985/solr/hydra-test/terms?terms.fl=depositor_ssim&terms.sort=count&wt=json&omitHeader=true
```
{"terms":{"depositor_ssim":["user1@example.com",4,"user2@example.com",1]}}

```

**Comment by mjgiarlo** [comment]
Buh. Is the TermsComponent counting other objects like ListNodes or Permissions objects or the like?

**Comment by jcoyne** [comment]
@mjgiarlo none of those things have `depositor_ssim` indexed on them.

**Comment by mjgiarlo** [comment]
@jcoyne I don't suppose you can convince Solr to give you more information about those 4 things?

**Pull request merged**
