### PR TITLE
Updates README for v6.2.0.

### PR DESCRIPTION
**Pull request by afred**
[ci skip]

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@afred Thanks for the PR!  We just released 6.2.0 today. (Heh!)  Could you rework this? (Ideally we would find a way to get around naming the specific version in the README, I guess...)

**Comment by afred** [comment]
actually, I was thinking the version _should_ be in the install instructions, and should be accessible via version-specific branch. E.g. the README that refers to 6.1 is available when you select the `6.1-stable` branch.

**Comment by mjgiarlo** [comment]
Good call, @afred. I've updated the release process to include this step: https://github.com/projecthydra/sufia/wiki/Release-management-process/_compare/86ca5a847fcdf49f71f1c51997180417e9f34138...11ddcd97ff87acf6e3b1385e96139557c0d8a1e1

**Comment by mjgiarlo** [comment]
For now, are you :ok: updating the PR to reflect the current version? And from here on out, we'll follow the pattern you suggest.

**Comment by afred** [comment]
sure... stand by..

**Comment by afred** [comment]
of course, the caveat to this approach, if you want accurate installation steps for previous releases, you'll have to go back and either ensure the instructions are accurate, or fix them in the README and cut a patch release.... e.g. fix installation instructions for 5.0 and cut a v5.0.1 release.

**Pull request merged**
