### PR TITLE
[WIP] Enable a simple mediated deposit workflow

### LINKED ISSUE #2628: Enable a simple mediated deposit workflow
To get started on mediated deposit work, create a feature flipper that allows an admin to enable or disable mediated deposit.  When turned on, depositing a work should not immediately publish it. Rather, the work should be marked as inactive and should notify administrative users that a new item is available to review/publish.  The default setting for mediated deposit should be "off"

The feature flipper should be implemented using the flipflop gem the same way admin sets is toggled on and off (see https://github.com/projecthydra/sufia/commit/3612d5ee627e320a52bc5687179119ddf98bcc8b and https://github.com/projecthydra/sufia/commit/3b4fd55527748f053e92f382fd8491c587208ccf)

### PR DESCRIPTION
**Pull request by scholarworks**
Fixes #2628 ; refs #2628 

This simply adds the configurable option in the administrative dashboard that will be used to enable a mediated deposit workflow.

Changes proposed in this pull request:
* add feature "enable_mediated_deposit"

@projecthydra/sufia-code-reviewers

NOTE: At this time, I am still waiting for completion of the CLA.

### CODE REVIEW

**Comment by scholarworks** [comment]
screenshot 2016-09-06 16 46 17

**Comment by scholarworks** [comment]
This was before I changed the description to "Turn on mediation for all deposits"

screenshot 2016-09-06 16 46 17

**Comment by mjgiarlo** [comment]
@scholarworks can you also add test coverage to `spec/models/flipflop_spec.rb`?

**Comment by scholarworks** [comment]
@mjgiarlo done (i think). Copied and updated the assign_admin_set for enable_mediated_deposit.

**Comment by jcoyne** [comment]
@scholarworks now, rubocop is going to complain that you didn't use the correct indenting.  Run `bundle exec rubocop --autocorrect` and it'll fix it for you.

**Comment by scholarworks** [comment]
@jcoyne Just saw that and committed a change.

**Comment by mjgiarlo** [comment]
The spacing in the spec looks off, too.

**Comment by mjgiarlo** [comment]
Looks solid to me! Travis did a weird thing on one of the builds so I restarted it. I'm guessing that will also fix the coveralls reporting. And then... we wait for CLAs.

**Comment by mjgiarlo** [comment]
Closing: superseded by #2645. Thanks for contributing, @scholarworks!

**Pull request closed without merging**
