### PR TITLE
Test with Rails 4.2.6

### PR DESCRIPTION
**Pull request by jcoyne**
@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
Dies with this error:
```
Bundler could not find compatible versions for gem "mime-types":

  In Gemfile:
    sufia (>= 0) ruby depends on
      sufia-models (= 6.6.0) ruby depends on
        hydra-derivatives (~> 1.0) ruby depends on
          mime-types (~> 2.3) ruby

    rails (= 4.2.6) ruby depends on
      actionmailer (= 4.2.6) ruby depends on
        mail (>= 2.5.4, ~> 2.5) ruby depends on
          mime-types (3.0)
/home/travis/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.9/lib/bundler/source/git/git_proxy.rb:151:in 
```

**Comment by jeremyf** [comment]
@jcoyne For reference, Sipity has Rails 4.2.6 and I believe you need gem `mail ~> 2.6.4`

**Comment by jcoyne** [comment]
I'm cutting a 1.2.0 release of hydra-derivatives to support that.

**Comment by cam156** [comment]
Looking good!  Just waiting on Travis.

**Comment by jeremyf** [comment]
"Stay on target! Stay on target!"

**Comment by cam156** [comment]
@jcoyne looks like it is going to fail due to poltergeist being missing.

**Comment by jcoyne** [comment]
"Eject!!!! Eject!!!"

**Pull request merged**
