### PR TITLE
Remove tagcloud widget from the home page

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mtribone** [comment]
:clap:

**Comment by jcoyne** [comment]
Is there a rationale for this?  I'm not arguing against this proposal, but I wonder if concerned parties agree with removing it.

**Comment by cbeer** [comment]
@mjgiarlo enthusiastically suggested throwing it away.

**Comment by mtribone** [comment]
We *may* need to keep it at Penn State, but might just be able to add it at the ScholarSphere level. However, it doesn't get a lot of hits when I take a quick look at analytics.

**Comment by jcoyne** [comment]
It seems like it could be in a plugin if more than one person wants it.

**Comment by mtribone** [comment]
Feb 29 through March 29 nobody clicked on the tag cloud in ScholarSphere...

**Comment by mjgiarlo** [comment]
Refs #1611

**Pull request merged**
