### PR TITLE
Removing nil or empty string identifiers from CreateWithFilesActor

### LINKED ISSUE #2051: If file upload errors, then work creation fails.
Because the file upload sets a hidden field on the page with no value.  Then when you submit a work it looks for an uploaded file with the ID of nil:
```
ActiveRecord::RecordNotFound (Couldn't find all Sufia::UploadedFiles with 'id': (, 1) (found 1 results, but was looking for 2)):
  activerecord (4.2.6) lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
  activerecord (4.2.6) lib/active_record/relation/finder_methods.rb:467:in `find_some'
  activerecord (4.2.6) lib/active_record/relation/finder_methods.rb:426:in `find_with_ids'
  activerecord (4.2.6) lib/active_record/relation/finder_methods.rb:71:in `find'
  activerecord (4.2.6) lib/active_record/querying.rb:3:in `find'
  activerecord (4.2.6) lib/active_record/core.rb:131:in `find'
  /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/bundler/gems/sufia-9c1afba2bb55/app/actors/sufia/create_with_files_actor.rb:38:in `uploaded_files'
  /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/bundler/gems/sufia-9c1afba2bb55/app/actors/sufia/create_with_files_actor.rb:19:in `validate_files'
  /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/bundler/gems/sufia-9c1afba2bb55/app/actors/sufia/create_with_files_actor.rb:6:in `create'
  curation_concerns (1.0.0.beta3) app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
  /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/bundler/gems/sufia-9c1afba2bb55/app/actors/sufia/create_with_remote_files_actor.rb:6:in `create'
  curation_concerns (1.0.0.beta3) app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
  curation_concerns (1.0.0.beta3) app/controllers/concerns/curation_concerns/curation_concern_controller.rb:43:in `create'
```

We should probably remove any nil file upload ids in `create_with_files_actor.rb`

(BTW, the initial file upload failed because it was too big and exceeded the limit set in nginx)

### PR DESCRIPTION
**Pull request by jeremyf**
Removing nil or empty string identifiers

Following @jcoyne's suggestion of removing any nil file upload ids
as it relates to #2051 (e.g. "If file upload errors, then
work creation fails.")

Closes #2051

### CODE REVIEW

**Comment by awead** [comment]
@jeremyf does this also relate to #2066 ? It's a similar situation where `[""]` is getting passed in the parameters hash.

**Comment by jcoyne** [comment]
Can you check to see if the files attribute is or is not going through here? https://github.com/projecthydra/hydra-editor/blob/master/app/forms/hydra_editor/form.rb#L58-L64  I wonder if it makes sense to update that method?

**Comment by jeremyf** [comment]
@awead At first I had used `Array.wrap(uploaded_file_ids).compact` but assumed that I might get `[nil, 1, ""]` so I switched to `Array.wrap(input).select(&:present?)` which should catch that scenario.

**Comment by jeremyf** [comment]
@jcoyne I won't be able to check that in my allotted time today; And will be on a new spring at ND starting Monday. So could you add the issue to HydraEditor as a follow-up?

**Comment by jeremyf** [comment]
Bringing @projecthydra/sufia-code-reviewers into the conversation regarding the particular bug.

**Pull request merged**
