### PR TITLE
[wip] Browse everything

### PR DESCRIPTION
**Pull request by aeschylus**
Fixes #issuenumber ; refs #issuenumber

Present tense short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

Description can have multiple paragraphs and you can use code examples inside:

``` ruby
class PostsController
  def index
    respond_with Post.limit(10)
  end
end
```

Changes proposed in this pull request:
- 
- 
- 

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@aeschylus When you get a few minutes, can you update the description of this issue to say what work is remaining? Is it just to get the specs green, or is there more to it?

**Comment by aeschylus** [comment]
I closed this other issue related to this. https://github.com/projecthydra/sufia/issues/1884

This PR depends on a dependency (Browse Everything) being merged in in the correct form. Here's some more information from that closed (non)issue.

The goal with these changes is to allow the browse-everything feature to be initialised without placing javascript inside the template.

The change has to be made in the initialisation of the [BE component](https://github.com/projecthydra/browse-everything/tree/expose_as_class) (use a constructor); the initialisation boilerplate in views/curation_concerns/browse-everything in sufia, and an initialisation function needs to be added to the sufia app.js (shown in this PR). The reorganisation will work because the blacklight.onload function already binds to both the pageload (turbolinks) event and the domready events, so we don't need the initialisation code stuck in the template.

The outstanding Browse Everything work is in the [expose_as_class](https://github.com/projecthydra/browse-everything/tree/expose_as_class) branch

**Comment by jcoyne** [comment]
Can you make a PR in BrowseEverything?

**Comment by atz** [comment]
Branch could use a rebase, too.

**Comment by mjgiarlo** [comment]
@jcoyne expressed some interest in this issue on 12/20/2016. :smile:

**Comment by jcoyne** [comment]
I don't think we're ever getting back to this.

**Pull request closed without merging**
