### PR TITLE
Fix alignment of dropdown menu

### PR DESCRIPTION
**Pull request by awead**
Fixes an issue found in psu-stewardship/scholarsphere#90

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Would you mind whipping up before/after screenshots?  I find those quite helpful in UI-related PRs to visualize how the code deltas will work.

**Comment by awead** [comment]
@mjgiarlo 
before:
before
after:
after

**Comment by mjgiarlo** [comment]
:+1: though Travis is :unamused:

**Comment by awead** [comment]
@mjgiarlo it's going to fail until the AF 9.0.7/6 issue is fixed.

**Comment by mjgiarlo** [comment]
Oh, right. :frowning: 

Should we pin to 9.0.6 in the meantime?  @jcoyne recommended yanking 9.0.7 FWIW

**Comment by awead** [comment]
k. I'll submit another pr for that

**Pull request merged**
