### PR TITLE
Add an admin dashboard page

### PR DESCRIPTION
**Pull request by jcoyne**
@projecthydra/sufia-code-reviewers

Presently this is just a skeleton, but we'll eventually put more admin
reports and settings here.

The design looks like this:
screen shot 2016-08-25 at 4 41 07 pm

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Rebase? Also, can you include a screenshot of what your changes look like? (It's not the screenshot above, right?)

**Comment by jcoyne** [comment]
My version of the dashboard looks like this:
screen shot 2016-08-26 at 2 23 39 pm

**Comment by jcoyne** [comment]
@mjgiarlo we can't have a comment that says `TODO`? that seems screwy.

**Comment by mjgiarlo** [comment]
@jcoyne We can disable that rule entirely or add an ignore for that line. Here's how to disable it entirely in `.codeclimate.yml`:

```yaml
engines:
  # ... 
  fixme:
    # ... 
    enabled: false
```

**Pull request merged**
