### PR TITLE
Break locales out into their own files.

### PR DESCRIPTION
**Pull request by mjgiarlo**
Makes it easier to find and read i18n keys.

### CODE REVIEW

**Comment by jcoyne** [comment]
This is not easier for me.

**Comment by mjgiarlo** [comment]
@jcoyne Really? It makes sense to me to have one top-level namespace in the locale file and for that to correspond to the name of the file. That way I can know where I am generally without having to scroll up much and scan for whitespace to see how indented a key is.

**Comment by jcoyne** [comment]
Yes, my editor can just collapse the YAML blocks, so it's all nicely organized in on place. Now it's spread out over N files.

**Comment by jcoyne** [comment]
http://smartic.us/2009/04/06/code-folding-in-vim/

**Comment by jcoyne** [comment]
screen shot 2016-06-10 at 2 22 27 pm

**Comment by mjgiarlo** [comment]
I've got folding too, but am still offended by the length of that locale file. ;)

No biggie.

**Pull request closed without merging**
