### PR TITLE
WIP: Updating Sufia 6 to use hydra-head 9.6

### PR DESCRIPTION
**Pull request by awead**
I'm guessing we'll need a generator to upgrade folks from 6.5 to 6.6. Does this sound right, @mjgiarlo ?

### CODE REVIEW

**Comment by jcoyne** [comment]
@awead alternatively, we can fix hydra-head, so that it includes the correct modules instead of just warning.

**Comment by awead** [comment]
@jcoyne I defer to you since you're more up-to-date with that particular gem than I am.

**Comment by mjgiarlo** [comment]
@awead When @jcoyne says things like "we can fix {**x**}," I'm generally in support of fixing **x**. If not, yeah, a generator to facilitate the upgrade process would be awful convenient for folks.

**Comment by jcoyne** [comment]
Regardless of what we do to HydraHead / migration tools, this PR is great. :+1:

**Comment by mjgiarlo** [comment]
Travis is :angry:

**Comment by mjgiarlo** [comment]
Merged all the 6.x PRs I saw with passing tests, @awead. This one is red.

**Comment by awead** [comment]
@mjgiarlo yeah, this is to get Sufia 6 with HH 9.6, and therefore Blacklight 6... It still needs some work.

**Pull request closed without merging**
