### PR TITLE
Remove duplicate rights entry

### PR DESCRIPTION
**Pull request by cbeer**
Rights is already provided upstream in `curation_concerns`.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@cbeer It looks like this was intentionally added recently:

https://github.com/projecthydra/sufia/commit/5e92b455a5dbf6859c0e86111b8448350e9d570f

To deal with https://github.com/projecthydra/sufia/issues/1600

**Comment by mjgiarlo** [comment]
@cbeer Can you confirm that the rights field is still displayed in the UI after you made this change?

Tagging @hectorcorrea who worked on #1600.

**Comment by cbeer** [comment]
Yes -- there's another partial in play (`_attributes.html.erb`, perhaps?).

**Comment by hectorcorrea** [comment]
:+1:

**Pull request merged**
