### PR TITLE
Download aspectjrt jar to support m4a files

### PR DESCRIPTION
**Pull request by awead**
Supports testing of fulltext indexing of m4a files using Solr's Tika plugin. Fixes errors reported in #931

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:+1: if Travis is :smile_cat:

**Comment by jcoyne** [comment]
Travis is very :disappointed: today http://www.traviscistatus.com/

**Comment by mjgiarlo** [comment]
:ghost:

**Comment by mjgiarlo** [comment]
Yay, one build unstuck!

**Comment by awead** [comment]
Woo-hoo! :tada:

**Comment by mjgiarlo** [comment]
:ok: truly :+1: now.

**Pull request merged**
