### PR TITLE
Move notifications top level, right side

### LINKED ISSUE #1866: Red badges for Notifications should bubble up to Dashboard
The point of the red badge number is to alert users to unread notifications.  For this feature, the front end constantly polls the server/DB.  So it doesn't make sense that the moment of notification (i.e., the badge displaying a number) is hidden under the "Dashboard" drop-down.  

The user should be alerted to the emergence of pending notifications at the topmost layer of the interface (without any menus or modals open).  Probably the top bar elements should aggregate the alerts from their drop-down children.  In practice, that means "Dashboard" should show "Notifications" alerts.  (I'm unaware of any other dynamic alerts.)

### PR DESCRIPTION
**Pull request by atz**
Fixes #1866

### CODE REVIEW

**Comment by jcoyne** [comment]
It looks like this broke `spec/views/_toolbar.html.erb_spec.rb`

**Comment by atz** [comment]
Yep, will fix/migrate those expectations to the new context tomorrow.

**Comment by atz** [comment]
OK, relocated the test and pushed.  Passed locally.

**Comment by mjgiarlo** [comment]
@atz I don't believe this is related to your PR. Is it?

```
 1) proxy add proxy in profile creates a proxy
     Failure/Error: click_link "View Profile"
     
     Capybara::ElementNotFound:
       Unable to find link "View Profile"
     # ./spec/support/locations.rb:10:in `block in go_to_user_profile'
     # ./spec/support/locations.rb:8:in `go_to_user_profile'
     # ./spec/features/proxy_spec.rb:11:in `block (3 levels) in <top (required
```

**Comment by mjgiarlo** [comment]
Failures are unrelated to PR. (:unamused:)

**Pull request merged**
