### PR TITLE
Remove the well class

### PR DESCRIPTION
**Pull request by jcoyne**
This is sort of a matter of taste, but I feel we've used well gratuitously in the past. Usually this could be added by the application as a style if required.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Can you include a screenshot of this UI change?

**Comment by mjgiarlo** [comment]
Thoughts on this change? @mtribone @atz @ggeisler @aeschylus

**Comment by ggeisler** [comment]
FYI: I don't have Sufia or HyBox running locally yet so can't provide an opinion on UI questions without seeing examples. (I plan to install HyBox locally but was hoping to focus on finishing the user research and design deliverables before worrying about my development environment.)

**Comment by jcoyne** [comment]
Old way:
screen shot 2016-04-08 at 12 54 32 pm
screen shot 2016-04-08 at 12 54 41 pm
screen shot 2016-04-08 at 12 55 00 pm


New way:

screen shot 2016-04-08 at 12 56 05 pm
screen shot 2016-04-08 at 12 56 22 pm
screen shot 2016-04-08 at 12 56 32 pm

**Comment by ggeisler** [comment]
Thanks @jcoyne. Yes, I'd agree that removing the well is a good idea. I don't think using a well for large/main sections of content really makes sense. It's better for more supplementary content, generally at least.

**Comment by mjgiarlo** [comment]
Seeing at least four votes in favor, I'm merging. Thanks!

**Pull request merged**
