### PR TITLE
Add worthwhile work controllers in sufia

### PR DESCRIPTION
**Pull request by cam156**
This is an initial cut at grabbing the controller from worthwhile for the works model in sufia.

Feel free to hammer it.

If there are additional test I should have pulled over please let me know.

### CODE REVIEW

**Comment by scherztc** [comment]
Should we hold off on merging this and instead use it as a reference for our routing/controller/model needs in our own fix branches?

**Comment by scherztc** [comment]
And possibly use it as a conversation place for issues around these topics?

**Comment by cam156** [comment]
@scherztc I think merging it may help with the other tickets, but we should discuss it.

**Comment by scherztc** [comment]
Glen and I have been discussing it this morning and rather than cut/paste code from your branch we came to the agreement that it would be better to merge this in, also.  I will merge it.

**Pull request merged**
