### PR TITLE
Don't show update order unless there are featured works. Fixes #865

### LINKED ISSUE #865: When no works have been featured and 'Save Order' is clicked an error is raised
As an admin user on the home page, given that no works have been featured, when 'Save Order' is clicked, results in an error page

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Should this also include a view spec that ensures the button isn't there, or do folks think this is sufficiently well tested already?

**Comment by jcoyne** [comment]
@mjgiarlo what do you think?

**Comment by mjgiarlo** [comment]
I think it'd be good to see one.

**Comment by jcoyne** [comment]
@mjgiarlo added some tests.

**Comment by mjgiarlo** [comment]
Failed.

**Pull request merged**
