### PR TITLE
Remove has_access? method

### PR DESCRIPTION
**Pull request by jcoyne**
This was not doing anything.  If this functionality is needed it should
be handled by CanCan

### CODE REVIEW

**Comment by awead** [comment]
This is doing something for Scholarsphere:

https://github.com/psu-stewardship/scholarsphere/blob/develop/app/controllers/application_controller.rb#L85

But it's more about negotiating access via Devise. We can remove it here, but those upgrading from Sufia 6 will need to be aware.

@cam156 thoughts?

**Comment by jcoyne** [comment]
@awead is there some reason you can't negotiate access using CanCan?

**Comment by cam156** [comment]
@awead Can you add a ticket to ScholarSphere to add the has_access into the overrides and reference this PR.  That way it will not get lost.

**Comment by jcoyne** [comment]
For Scholarsphere it may be better to override the Devise sessions controller and put an `after_filter :has_access?, only: :create`

**Comment by awead** [comment]
We're using it to check if the authenticated user exists in LDAP, so it ought to be a `before_filter`. So I guess we can do that with CanCan: `can :has_ldap`? But what I'm wondering is why this kind of check isn't earlier on, in the Devise::Behaviors level. Seems like we should immediately deny any authenticated user that's not in LDAP.

**Comment by awead** [comment]
See https://github.com/psu-stewardship/scholarsphere/issues/315

**Pull request merged**
