### PR TITLE
Use kaminari_route_prefix instead of custom kaminari fork

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by rotated8** [comment]
:tada:

**Comment by awead** [comment]
Do we want to pin to rubocop 0.37.2? I'm getting this yuckiness:
```
/Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:40:in `require': cannot load such file -- /Users/awead/Projects/Github/projecthydra/sufia/rubocop-rspec (LoadError)
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:40:in `block in load_file'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:39:in `each'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:39:in `load_file'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:99:in `configuration_from_file'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_store.rb:41:in `for'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/cli.rb:88:in `apply_default_formatter'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/cli.rb:26:in `run'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/bin/rubocop:14:in `block in <top (required)>'
	from /Users/awead/.rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/bin/rubocop:13:in `<top (required)>'
	from /Users/awead/.gem/ruby/2.2.3/bin/rubocop:23:in `load'
	from /Users/awead/.gem/ruby/2.2.3/bin/rubocop:23:in `<main>'
```

**Comment by mjgiarlo** [comment]
wat
i cant even

**Comment by mjgiarlo** [comment]
@awead Yes, I now support this and it's been a long time coming. If you want to pin that in a PR... would you also mind adding a new step to our release management docs that says something akin to, "once the new release has been cut, you should consider updating the pinned Rubocop dependency, or ticketing that work for the next release, so that the Sufia codebase stays up to date with the latest community style guide."

**Comment by mjgiarlo** [comment]
Travis is :red_circle: so we can't merge this yet.

**Comment by jcoyne** [comment]
@cbeer Isn't blacklight pulling in `kaminari`?  Won't we now have `kaminari` +`kaminari_route_prefix` loaded? See https://github.com/projectblacklight/blacklight/blob/fc5ac227b2f46528b5ae7c43ebc68cb310d1d31b/lib/blacklight.rb#L2

**Comment by mjgiarlo** [comment]
Don't we need both, still? `kaminari_route_prefix` is a layer on top of `kaminari`, I thought.

**Comment by jcoyne** [comment]
@cbeer @mjgiarlo Yes, I see now. I've updated the readme in kaminari_rooute_prefix.

**Comment by mjgiarlo** [comment]
:clap: @jcoyne

**Comment by mjgiarlo** [comment]
@cbeer This PR needs to be rebased now that @awead's PR to fix Rubocop has been merged.

**Pull request merged**
