### PR TITLE
Use UTF8 encoding for Endnote files

### PR DESCRIPTION
**Pull request by awead**
Sorry, forgot to add this earlier.

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by awead** [comment]
I don't think this is needed because config.action_dispatch.default_charset should cover that.

**Comment by cam156** [comment]
@awead do we have a test that makes sure config.action_dispatch.default_charset is set it does indeed end up in the output to the user?  I wonder if send data is overriding the default.

**Comment by awead** [comment]
@cam156 no, the setting wasn't there before. FWIW, I'm not seeing any difference with the option set and/or with `charset=utf-8` in the header. The file is downloaded as `charset=us-ascii` each time, unless I'm not checking it correctly.

**Comment by awead** [comment]
@cam156 ok, I can now confirm utf-8 download. I just needed to use non-ascii characters in the title. It's downloading as utf-8 _without_ adding the charset in the or even specifying it in the config... so meh. I'm going to add the config option in anyway in Scholarsphere, but we don't need the add the charset in the header, I'm closing this PR.

**Pull request closed without merging**
