### PR TITLE
Remove the duplicate showing of title and move the description up above ...

### PR DESCRIPTION
**Pull request by cam156**
...the table to match collection show view.

### CODE REVIEW

**Comment by jcoyne** [comment]
@cam156 make sure you check that title and description didn't fall off the edit form.

**Comment by jcoyne** [comment]
I think the way you want to accomplish this is by changing _show_descriptions.html.erb like this:

```erb
<% present_terms(@presenter, @presenter.terms_with_values - [:title, :description]) do |r, term| %>
```

**Comment by cam156** [comment]
@jcoyne Thanks for the tip.  I was hoping it was really simple, but that was not the case.

**Comment by awead** [comment]
@cam156 props for the "in progress" label. I think we should make use of that more often in our workflow!

**Comment by hectorcorrea** [comment]
Looks good to me. I love the array subtraction `@presenter.terms - [:title, :description]` to get the list of terms to render.

**Pull request merged**
