### PR TITLE
refactoring batch_controller to behavior for downstream overridding

### PR DESCRIPTION
**Pull request by weiweishi**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
One of the builds failed but it looked very :dizzy_face:, so I'm restarting that build.

**Comment by mjgiarlo** [comment]
Thanks much for the PR, @weiweishi!

**Comment by weiweishi** [comment]
Thanks @mjgiarlo. Ran into this while I was working on the metadata forms.

**Comment by mjgiarlo** [comment]
:clap:

**Pull request merged**
