### PR TITLE
Adding enable_mediated_deposit as a flippable feature

### LINKED ISSUE #2628: Enable a simple mediated deposit workflow
To get started on mediated deposit work, create a feature flipper that allows an admin to enable or disable mediated deposit.  When turned on, depositing a work should not immediately publish it. Rather, the work should be marked as inactive and should notify administrative users that a new item is available to review/publish.  The default setting for mediated deposit should be "off"

The feature flipper should be implemented using the flipflop gem the same way admin sets is toggled on and off (see https://github.com/projecthydra/sufia/commit/3612d5ee627e320a52bc5687179119ddf98bcc8b and https://github.com/projecthydra/sufia/commit/3b4fd55527748f053e92f382fd8491c587208ccf)

### PR DESCRIPTION
**Pull request by randalldfloyd**
Fixes #2628 ; refs #2628

Formalizes WIP #2638, which would require contributor's CLA to be resolved in order to merge.

This simply adds the configurable option in the administrative dashboard that will be used to enable a mediated deposit workflow.

Changes proposed in this pull request:

    add feature "enable_mediated_deposit"

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by scholarworks** [comment]
Awesome.

**Comment by mjgiarlo** [comment]
Build failing because #2646 needs to be merged first. After it's merged, can you rebase your branch on master, @randalldfloyd?

**Comment by randalldfloyd** [comment]
@mjgiarlo Sure thing. This was all passing locally after I rebased on last time before opening the PR, maybe I didn't refresh my internal test app after doing so. I'm always puzzled by "passed ci locally but failed on the PR".

**Comment by mjgiarlo** [comment]
Thanks, @randalldfloyd !

**Comment by jcoyne** [comment]
Should we hold off on merging this until 7.2 is released?

**Comment by mjgiarlo** [comment]
@jcoyne It's blocking other tickets atm. Why do you think we should wait?

**Comment by jcoyne** [comment]
@mjgiarlo Because if  you release 7.2, and people flip the switch, nothing will happen. This would not be what users would expect.

**Comment by hortongn** [comment]
@jcoyne @mjgiarlo So should we merge all of the mediated deposit tickets into a separate fork/branch until we reach a point that this feature is baked enough to go into a release?  Then merge it into master as one big squashed commit?

**Comment by jcoyne** [comment]
@hortongn that's a fine idea.

**Comment by mjgiarlo** [comment]
@hortongn @jcoyne OK, then we can use a new branch for mediated deposit that tracks master. It adds some additional overhead (remembering to: update the branch with changes to `master`, branch off the new branch, submit PRs against the new branch, etc.) but it's probably for the best.

@randalldfloyd I'll create the new branch in a little bit, at which point you can rebase this PR (again, sorry).

**Comment by mjgiarlo** [comment]
OK, please rebase this on `mediated_deposit_epic`, @randalldfloyd

**Comment by hortongn** [comment]
+1 thanks guys

**Comment by randalldfloyd** [comment]
+1 This makes good sense to me, I'll get on that rebase and switch the target for this PR.

**Comment by randalldfloyd** [comment]
@mjgiarlo So as a workflow sanity check, I'm thinking I edit this PR and change the target from master to mediated_deposit_epic, and the push an update to my remote branch that has since been rebased on the new branch. Assuming that might that kick off 2 separate CI checks, is there a better way to do it?

**Comment by mjgiarlo** [comment]
@randalldfloyd I've taken the liberty of changing the base for this PR. You can do that via the GitHub UI by clicking "Edit" up by the title, and then right under the title there's a dropdown box for base.

For rebasing... yeah, checkout master, pull latest, checkout your branch, rebase on master, push your change. You can squash your commits if you'd like. Then force-push to your branch and the PR should pick up the changes.

**Comment by hortongn** [comment]
@randalldfloyd After you rebase and push up your branch again, I'll merge when the checks are complete.  I've already tested and verified that the flipper displays in the admin settings and works as intended.

**Comment by randalldfloyd** [comment]
@mjgiarlo Got it, thanks.  Maybe I misunderstood the first time, I thought I needed to rebase from mediated_deposit_epic instead of master but thanks for going ahead and changing the base for the PR.

**Comment by hortongn** [comment]
@randalldfloyd I do think you need to rebase against mediated_deposit_epic.  This PR won't allow a merge because it thinks your branch is out of date.

**Comment by randalldfloyd** [comment]
@hortongn Yeah I rebased against the new epic branch yesterday so I'm just going to force push it and see what happens.

**Comment by randalldfloyd** [comment]
Okay this is getting frustrating. CI fails hard on a basic devise dependency and coverage decreases 96%?  My local branch passes everything locally after rebasing to mediated_deposit_epic.  This morning when I looked at the PR, the codeclimate and dependency-ci checks were still waiting for status, presumably after the PR was changed to use the epic branch as the base.

**Comment by mjgiarlo** [comment]
@randalldfloyd I'll take a look.

**Comment by hortongn** [comment]
@mjgiarlo @randalldfloyd I closed and restarted this PR over the weekend because the codeclimate and depenency-ci checks we stuck in limbo, but now Travis is failing after running again.  And the two other checks are still not running. :p

**Comment by jcoyne** [comment]
@hortongn We need to merge https://github.com/projecthydra/sufia/pull/2662 to fix the issues.

**Comment by randalldfloyd** [comment]
@hortongn #2662 just merged so I'm rebasing from master and running CI locally now...

**Comment by mjgiarlo** [comment]
@randalldfloyd #2666, which was blocking this and other branches, has now been merged to `master` and I fast-forwarded `mediated_deposit_epic`. can you rebase your branch on the (now updated) `mediated_deposit_epic` branch, squash your commits into one, and push? 

(And for the future, are you cool w/ pushing your working branches to projecthydra/sufia vs. randalldfloyd/sufia? That way other folks can push to your branches.)

**Comment by randalldfloyd** [comment]
@mjgiarlo Is there still some movement in master that I should wait for? I'm even with the mediated_deposit_epic containing up to #2666 but I get two failing tests locally on a full CI after regenerating the test app and bundling fresh.

**Comment by mjgiarlo** [comment]
@randalldfloyd GitHub says your branch is not yet caught up with `mediated_deposit_epic`. Did you do [the steps I suggested above](https://github.com/projecthydra/sufia/pull/2645#issuecomment-246439937)?

**Comment by randalldfloyd** [comment]
@mjgiarlo I wasn't clear I guess; I didn't push back up to my branch because it was failing locally and I didn't see the point in creating another failing PR.  I was totally even with the epic branch but I'll rebase from master this morning in case there's been more commits. But yes, I was definitely even with everything at that time.

**Comment by hortongn** [comment]
I opened a WIP PR this morning for my issue and I have Randall's Flipflop code included in that branch.  The only complaint Travis has is a Rubocop offense on my code.  So Randall's code in my branch doesn't upset Travis even though it does produce one failure in this branch.

**Comment by mjgiarlo** [comment]
@randalldfloyd OK, sorry for the misunderstanding. I was confused because it looked like the builds here restarted, so I assumed you pushed code.

**Comment by mjgiarlo** [comment]
@randalldfloyd can you gist the two failures you're getting and confirm you've got all the latest from `mediated_deposit_epic` (which I caught up with `master` yesterday)?

**Comment by randalldfloyd** [comment]
@mjgiarlo If convenient could you fast forward the branch again since there's been commits since yesterday? I'm currently running CI after rebasing to master just to see if I could get the failures to go away - it didn't seem to make sense to rebase against the epic branch since it is already stale.

**Comment by randalldfloyd** [comment]
@mjgiarlo @hortongn Closing this out and basing new PR #2680 on a sufia repo branch at https://github.com/projecthydra/sufia/tree/2628-mediated-deposit, which is currently at least passing the travis-ci/push build.

**Pull request closed without merging**
