### PR TITLE
Fix terms of service feature test.

### LINKED ISSUE #1038: Test and its opposite both pass
To recreate this bug, negate line 22 of spec/features/ingest_upload_files
https://github.com/projecthydra/sufia/blob/master/spec/features/ingest_upload_files_spec.rb#L22

e.g.,
        expect(page).not_to have_content "Please accept Deposit Agreement before you can upload."

run the test
$ bundle exec rake spec SPEC=spec/features/ingest_upload_files_spec.rb

I am seeing the test pass both ways. Appreciate an attempt to replicate.

### PR DESCRIPTION
**Pull request by hackmastera**
Fix #1038.

### CODE REVIEW

**Comment by jcoyne** [comment]
Probably failed due to https://twitter.com/traviscistatus/status/592902357144498176

**Comment by hackmastera** [comment]
Thanks for looking out. I guess I will check in later today.

**Comment by awead** [comment]
@hackmastera you don't have to open another PR to re-run the Travis tests. If Travis is being weird, you can re-run it from the Travis console by clicking on the "Details" link in the active PR. Once it passes, you'll see a green "Able to merge" in the PR.

**Comment by hackmastera** [comment]
@awead I googled and hunted for such an option but I was unable to find it. I think it is only available to project owners. Thanks!

**Pull request closed without merging**
