### PR TITLE
Fixes contrast issues with font color and badge color in the stats on dashboard

### PR DESCRIPTION
**Pull request by mtribone**

### CODE REVIEW

**Comment by mtribone** [comment]
Old view had a contrast ratio of 1.6 to 1

screen shot 2015-06-10 at 1 56 19 pm

**Comment by mtribone** [comment]
New view is 13.2 to 1 for yellow badge and 5.7 to 1 for grey badge

screen shot 2015-06-10 at 1 56 42 pm

**Comment by awead** [comment]
:+1: My only comment is are there any other places that use these colors or contrasts? I think no, but just asking.

**Comment by mtribone** [comment]
They appear in the dashboard index partial "_stats.html.erb" and override the default Bootstrap badge. There is one instance of .badge in the *cough* tagcloud, but it is specified as a li .badge. Perhaps I should make these more specific to the dashboard by naming the class .dashboard-badge and .dashboard-badge-optional?

**Comment by cam156** [comment]
:+1: naming with dashboard!

**Comment by mtribone** [comment]
Reworking the class name and adding in the rounded corners and spacing. I'll amend my commit.

**Comment by mtribone** [comment]
Hmmm...wait a minute...this is already nested. I have .dashboard on the content container and have nested the declaration, so only .dashboard .badge will get the colors. The default .badge is untouched.

**Comment by mtribone** [comment]
Ready to go!

**Pull request merged**
