### PR TITLE
Use hydra-batch-edit 2.x that removes its dependency on hydra-collections

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by jcoyne** [comment]
@cbeer I added a commit which I *think* finally cuts ties with hydra-collections

**Comment by cbeer** [comment]
Ok. I'll get the test suite passing for `hydra-batch-edit` and get a new release out.

**Comment by atz** [comment]
Seems like some substantive errors in CI.

**Comment by mjgiarlo** [comment]
Yep, still busted because of missing helpers.

**Pull request merged**
