### PR TITLE
Makes sure the date_uploaded is initialized...

### LINKED ISSUE #1467: Date uploaded is not being displayed for works on the dashboard
http://localhost:3000/dashboard/works

### PR DESCRIPTION
**Pull request by hectorcorrea**
...when creating a default_work. Fixes #1467

### CODE REVIEW

**Comment by grosscol** [comment]
I thought that GenericWork was the default work created by the sufia install process.  To what end are we defining a DefaultWork class that doesn't inherit from any of the PCDM or Hydra::Works classes?

**Comment by jcoyne** [comment]
I have the same concerns as @grosscol

**Comment by jcoyne** [comment]
I see. DefaultWork is a service class. @hectorcorrea can you move it
out of app/models? I don't think it belongs there.

**Comment by hectorcorrea** [comment]
@grosscol @jcoyne Good idea. I made the class a service instead of a model.

**Comment by mjgiarlo** [comment]
You'll want to rebase this on `master` once #1490 is merged.

**Comment by hectorcorrea** [comment]
@mjgiarlo rebased

**Pull request merged**
