### PR TITLE
Add install template for quicker installation

### PR DESCRIPTION
**Pull request by mjgiarlo**
Using a template, and updating it within every release, allows us to simplify the instructions for developers who wish to get Sufia up and running in development mode very quickly. Also helps automate manual steps such as the inclusion of the `flipflop` gem from GitHub.

README and release management process have already been updated to reflect the new template.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jcoyne oops, yes. doing too many things and didn't push my change.

**Comment by elo2112** [comment]
Looks like rails_command is only available on rails 5 and not in 4.2:

http://guides.rubyonrails.org/v4.2/rails_application_templates.html

Other commands look good though

**Comment by mjgiarlo** [comment]
Working on it. Thanks, @elo2112!

**Comment by elo2112** [comment]
New changes look good, but I wanted to test the template to be sure.  Encountered something strange.

This works (latest Rails 4 release):

rails _4.2.7.1_ new sufia_rails4 -m https://raw.githubusercontent.com/projecthydra/sufia/c3265630548baa4bda9164ff86d43bfd2e263300/template.rb

But this gives me some issues (latest Rails 5 release):

rails _5.0.0.1_ new sufia_rails5 -m https://raw.githubusercontent.com/projecthydra/sufia/c3265630548baa4bda9164ff86d43bfd2e263300/template.rb

The command above ends up creating a massive number of processes on my computer:

$ ps ux | wc -l
     692

So many, in fact, that I can't create new ones:

$ ps ux | wc -l
-bash: fork: Resource temporarily unavailable

And I start seeing tons of repeating messages like this in my console:

```
E, [2016-10-12T22:44:45.737644 #32308] ERROR -- : fsevent: running worker failed: Resource temporarily unavailable - ~/.rvm/gems/ruby-2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch:~/.rvm/gems/ruby-2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/fsevent.rb:106:in `popen'
~/.rvm/gems/ruby-2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/fsevent.rb:106:in `open_pipe'
~/.rvm/gems/ruby-2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/fsevent.rb:37:in `run'
~/.rvm/gems/ruby-2.3.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:68:in `_run_worker'
~/.rvm/gems/ruby-2.3.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:77:in `block (2 levels) in _run_workers_in_background'
~/.rvm/gems/ruby-2.3.0/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: ~/.rvm/gems/ruby-2.3.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:67:in `_run_worker'
```

That said, the template does eventually finish running.  This is on Mac OS 10.11.6 with Ruby 2.3.  Is anyone else experiencing anything similar?

**Comment by jcoyne** [comment]
@elo2112 I think you're running into this issue with listen/rails: https://github.com/rails/rails/issues/26158

**Comment by mjgiarlo** [comment]
@elo2112 Ha, @cgalarza ran into the same yesterday, and I added this to the Sufia Dev Guide: https://github.com/projecthydra/sufia/wiki/Sufia-Development-Guide#install-problems

**Comment by elo2112** [comment]
@mjgiarlo Ah!  Just caught up on yesterday's Slack chat and I see what you're referring to, thanks.  All good with --skip-listen.  PR looks good to me.

**Pull request merged**
