### PR TITLE
Set the RDF type of GenericFile to pcdm:Object

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by awead** [comment]
@jcoyne I'm assuming this is to be for a 6.1 release?

**Comment by cam156** [comment]
@awead I think jcoyne was think for 6.0.  That way when we move to PCDM the object is already typed correctly.

**Comment by jcoyne** [comment]
@awead yeah, we should release this ASAP 6.0.1

**Comment by mjgiarlo** [comment]
:+1: to a 6.0.1 release.

**Pull request merged**
