### PR TITLE
Configure mini_magick to use posix_spawn instead of open3.

### PR DESCRIPTION
**Pull request by hackmastera**
Fixes projecthydra/sufia#1325

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Looks good to me. @jcoyne @cam156 @terrellt @awead

**Comment by awead** [comment]
:+1:

**Comment by hackmastera** [comment]
I think this will only fix the problem for newly-generated projects. Not sure how this would get to be part of a release's upgrade path.

**Comment by mjgiarlo** [comment]
@hackmastera You can use an approach like the one you see here:

https://github.com/hackmastera/sufia/commit/9fd48874f034299f07fafab893f44172a1f52121

Basically, put your generator change into its own named generator and invoke that from the install generator. That way we can hook into the named generator in the next upgrade. Does that make sense?

Feel free to update the release notes (History.md) in this PR too so that when we're cutting the next release (which will probably be quite big since we haven't cut one in a while) we include this in the notes.

**Comment by hackmastera** [comment]
@mjgiarlo does that look right? if so i will squash.

**Pull request merged**
