### PR TITLE
Show last saved date on work show page

### LINKED ISSUE #1855: Work show page -- display last saved date in right column
See wireframe https://wiki.duraspace.org/x/DAF6B

### PR DESCRIPTION
**Pull request by jcoyne**
@projecthydra/sufia-code-reviewers

Fixes #1855

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Add spec coverage?

**Comment by jcoyne** [comment]
> Add spec coverage?
No uncovered lines were added.

**Comment by mjgiarlo** [comment]
If tomorrow I delete the line you added, the tests would still pass.

**Comment by jcoyne** [comment]
@mjgiarlo that is true, but that would not change the coverage of the code, which is what you asked for.

**Comment by mjgiarlo** [comment]
Why can't you read my mind yet?

**Comment by jcoyne** [comment]
Added a test :trollface:

**Pull request merged**
