### PR TITLE
Updated to support ActiveFedora 9.2.0

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by cam156** [comment]
@jcoyne I would guess this is incomplete.  I would guess this line is also needing to be changed: https://github.com/psu-stewardship/sufia/blob/master/app/views/collections/_form_for_select_collection.html.erb#L16

**Comment by mjgiarlo** [comment]
Superseded by #1234?

**Comment by mjgiarlo** [comment]
Closed by #1234. (Delete the branch if this is :ok:, @jcoyne.)

**Comment by jcoyne** [comment]
:ok:

**Pull request closed without merging**
