### PR TITLE
Fixes background color of facet X when filtering.

### PR DESCRIPTION
**Pull request by mtribone**
Collision with .remove class https://github.com/psu-stewardship/scholarsphere/issues/136

### CODE REVIEW

**Comment by jcoyne** [comment]
What is it clashing with? Where is the `.remove` with the red background defined?

**Comment by mtribone** [comment]
It uses the same class name for the X button on "You searched for"

screen shot 2015-06-08 at 4 11 41 pm

**Comment by mtribone** [comment]
And also the remove button on the metadata page

screen shot 2015-06-08 at 4 13 36 pm

**Comment by mtribone** [comment]
.remove is in _buttons.scss file in assets > stylesheets > sufia

**Comment by jcoyne** [comment]
Why don't we make _buttons.css more specific to apply it's syles only where needed, rather than adding more specific styles that keep the defaults everwhere else?

**Comment by mtribone** [comment]
Gotcha. I'll rework it.

**Pull request merged**
