### PR TITLE
Add audit log migration to upgrade generator 700, fixes #2706

### LINKED ISSUE #2706: Create db migration to change 'dsid' to 'file_id' on table "checksum_audit_logs"
To upgrade sufia 6 apps to sufia 7

### PR DESCRIPTION
**Pull request by hackmastera**
@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
https://travis-ci.org/projecthydra/sufia/jobs/161351356#L1843 
```
No such column: checksum_audit_logs.dsid

/home/travis/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:501:in `column_for'

/home/travis/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:487:in `rename_column'

/home/travis/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'

/home/travis/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'

/home/travis/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'

/home/travis/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'

/home/travis/build/projecthydra/sufia/.internal_test_app/db/migrate/20160920152147_change_audit_log_dsid_to_file_id.sufia.rb:4:in `change'
```

I think this migration should be created by the upgrade generator, not in the standard migrations.

**Comment by hackmastera** [comment]
Agree; will move it.

**Comment by jcoyne** [comment]
@hackmastera can this be closed?

**Comment by hackmastera** [comment]
It is def. needed for upgrade, but I couldn't figure out where to put it. would appreciate some guidance.

**Comment by cam156** [comment]
@hackmastera I would put the migration file in the templates here: https://github.com/projecthydra/sufia/tree/master/lib/generators/sufia/templates and then copy it over in the migration generator: https://github.com/projecthydra/sufia/blob/master/lib/generators/sufia/upgrade700_generator.rb

**Comment by hackmastera** [comment]
closing to reopen against 7.2-migration

**Pull request closed without merging**
