### PR TITLE
Pin to Rubocop 0.37

### PR DESCRIPTION
**Pull request by awead**
Because, rubocop....

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by awead** [comment]
ping @mjgiarlo

**Comment by jcoyne** [comment]
@awead New `rake` gotcha `NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000003347350>`

**Comment by awead** [comment]
yeah, this - https://github.com/bbatsov/rubocop/commit/88a200e59e10868450ceb4316ffc600d9a09b95c

**Comment by awead** [comment]
We can either use rake < 11.0 or forge ahead with rubocop 0.38.

**Comment by jcoyne** [comment]
Onward, Ever Onward!

**Comment by mjgiarlo** [comment]
:clap:

:+1: once the build is :green_heart:

**Pull request closed without merging**
