### PR TITLE
Rename batchuser and audituser to batch_user and audit_user

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by cam156** [comment]
@jcoyne I realize the user methods were not previously tested, but how about some tests?  That would make coveralls happier.  Otherwise looks great!

**Comment by jcoyne** [comment]
You want test for deprecated methods that call their non deprecated counterpart?

**Comment by jcoyne** [comment]
Check this out. I increased the coverage without writing any tests.  This is why it's important not to put too much faith in the coverage number. 😉

**Comment by mjgiarlo** [comment]
@cam156 what do you think? is this ready to go, or do you think it needs more work?

**Pull request merged**
