### PR TITLE
Remove LocalIngestBehavior

### PR DESCRIPTION
**Pull request by jcoyne**
@projecthydra/sufia-code-reviewers

Browse anything can do this now.
Also remove other dead code including `Group`, `MySearchBuilder` and
`CreateWithCollectionsActor`

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jcoyne Didn't you just create `CreateWithCollectionsActor` last week?

**Comment by mjgiarlo** [comment]
@jcoyne Can you rebase this? See my other question above too.

**Comment by jcoyne** [comment]
@mjgiarlo I did just create it last week, but I moved that functionality down to CC.

**Comment by mjgiarlo** [comment]
(I realized that and merged. :clap:)

**Pull request merged**
