### PR TITLE
Makes the edit actions under thumbnail match browse view

### PR DESCRIPTION
**Pull request by mtribone**
Aligns the collection actions with both show and edit view for consistency.

### CODE REVIEW

**Comment by awead** [comment]
Looks good. Merge with when Travis is :ok:

**Comment by mtribone** [comment]
Collections show view with the actions under the thumbnail.

screen shot 2015-07-13 at 2 58 21 pm

**Comment by mtribone** [comment]
I'm the old edit version with the actions at the top:

screen shot 2015-07-13 at 3 00 44 pm

**Comment by mjgiarlo** [comment]
Much better! :clap: :sparkle: @mtribone

**Comment by mtribone** [comment]
I'm the new edit screen

screen shot 2015-07-13 at 3 03 18 pm

**Comment by mjgiarlo** [comment]
One failing test, but this is due to an intermittent poltergeist timeout which is unrelated to this PR.  Merging!

**Pull request merged**
