### PR TITLE
Avoid JS error when there are no admin sets on the page.

### LINKED ISSUE #3153: Javascript error on new work form
here's the error https://gist.github.com/hackmastera/541191707ccda58733519896b0f734ad

due to "Current user has no admin sets to deposit to" quoth @jcoyne!

### PR DESCRIPTION
**Pull request by jcoyne**
Prevents a null pointer error. Fixes #3153

### CODE REVIEW

**Comment by hackmastera** [comment]
just checked out this branch and tried it out. looks like the null has moved.

https://gist.github.com/hackmastera/9ae046cb40fcb69f4b2edfe9f3762acd

**Comment by hackmastera** [comment]
@jcoyne I can generate more javascript errors if I forget to even run the default_admin_set:create task: https://gist.github.com/hackmastera/33e416218fedfbf97da69997904351eb

Not sure how long you want to play this game, though.

**Comment by jcoyne** [comment]
@hackmastera I had a stupid typo.  Try again?

**Comment by hackmastera** [comment]
nice!

**Pull request merged**
