### PR TITLE
Use CurationConcerns::WorkRelation

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
CC PR has been merged.

**Comment by mjgiarlo** [comment]
:green_apple:!

Is this still WIP? Do we need changes to https://github.com/projecthydra/sufia/blob/master/spec/services/sufia/query_service_spec.rb first?

**Comment by jcoyne** [comment]
@mjgiarlo it's ready to merge. I'm not clear on why you are suggesting changes to `spec/services/sufia/query_service_spec.rb`

**Comment by awead** [comment]
@mjgiarlo are you okay with this one?

**Comment by mjgiarlo** [comment]
@jcoyne Not suggesting, just asking. The changes are a clean refactor, so I suspect we're already good.

**Pull request merged**
