### PR TITLE
Remove spec that tests Blacklight, not Sufia

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by awead** [comment]
@jcoyne do we have any integration tests that verify the facet search links work?

**Comment by jcoyne** [comment]
I don't know, but if we merge #2343, we won't even be using the `render_index_field_value` method from Blacklight.

**Comment by jcoyne** [comment]
In other words, not merging this PR, does not get us any closer to having an integration spec.

**Comment by mjgiarlo** [comment]
@awead @jcoyne I'm in favor of merging, but you raise good points about integration testing. Perhaps one of you could create a new issue for this, so we don't blindly trust Blacklight or lose track of this need?

**Comment by awead** [comment]
@jcoyne makes sense. so the doc_presenter in #2343 is now taking care of rendering the facet links, so having this test here is going to be superfluous anyway, right?

**Comment by jcoyne** [comment]
@awead that's correct.

**Comment by awead** [comment]
OK, I've put this here to remind us: #2345

**Comment by atz** [comment]
This is ill advised.  This tests **sufia's configuration of blacklight** and it represents tests that were directly cut out of different file and moved here.  The remaining tests are entirely superficial and do not test the different field configurations, helper_methods, itemprops, etc.  

Is preferable to REVERT to retain history rather than me adding this back in as a branch.  The fact that there is more/better integration testing to do doesn't get you out of actually addressing the cases that are covered here.

**Pull request merged**
