### PR TITLE
Moving admin statistics logic out of the controller.

### PR DESCRIPTION
**Pull request by carolyncole**
Specifically leaving the admin stats test alone to prove I did not break the original code

### CODE REVIEW

**Comment by cam156** [comment]
@jcoyne can you clarify what you mean by this all?   The SystemStats class? The calls to the SystemStats?

**Comment by jcoyne** [comment]
@cam156 I was thinking the call to system stats class could be encapsulated in the presenter, since it only sets variables on the presenter.

**Comment by cam156** [comment]
@jcoyne that make sense to me. I will work on that.

**Comment by cam156** [comment]
@jcoyne moved the stats admin calls to the presenter. Better?

**Comment by mjgiarlo** [comment]
Travis is :unamused: 

```
     Failure/Error: Sufia::AdminStatsPresenter.new.tap do |p|
     ArgumentError:
       wrong number of arguments (0 for 2)
```

**Comment by cam156** [comment]
Not sure why this is showing a failing build.   When you click trough to travis all builds passed.

**Comment by jcoyne** [comment]
Such an improvement! :clap:

**Pull request merged**
