### PR TITLE
Remove header. Panel is labeled by the tab

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mtribone** [comment]
@projecthydra/sufia-ui-ux-advisors We need some 👀  on this PR in the context of the home page. Do we need headings if the tabs are labeled?

**Comment by mjgiarlo** [comment]
@jcoyne Would it help the @projecthydra/sufia-ui-ux-advisors if a screenshot were included illustrating the change?

**Comment by jcoyne** [comment]
Before:
screen shot 2016-09-13 at 10 51 41 am

After:
screen shot 2016-09-13 at 10 52 24 am

**Comment by justcolin** [comment]
Hmm, the heading is useful for screenreader users (they use it to skip around the page). Would it be possible to have the unlinked tab to be encoded as an `h#` element?

**Comment by jcoyne** [comment]
@justcolin should there be similar headers on the other tabs? Currently there aren't.

**Comment by justcolin** [comment]
@jcoyne: Yup! Almost every significant section should have a header.

**Comment by justcolin** [comment]
That being said, if it were removed it wouldn't be a critical error, more of a nuisance.

**Comment by mjgiarlo** [comment]
Given what @justcolin has shared, how would you like to proceed on this one, @jcoyne?

**Comment by jcoyne** [comment]
Closing. I added the `sr-only` class to that `h2` (and added missing headers for other tabs) in a different PR

**Pull request closed without merging**
