### PR TITLE
Add additional rubocop style enforcement

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@cbeer The build is :green_apple: now. Is this still WIP or is it ready to go?

**Comment by cbeer** [comment]
Still a WIP, I want to remove 8a8257f before we merge this.

**Comment by cbeer** [comment]
422b617 should be reviewed, as it does introduce functional changes. We were relying on funky DateTime behavior (`DateTime.parse('2016-01-01') === DateTime.parse('2016-01-01').end_of_day`) in the tests, and probably didn't capture our true intent.

**Comment by mjgiarlo** [comment]
@cam156 Thoughts on 422b617 in this PR?

**Comment by cam156** [comment]
@mjgiarlo It seems like a good idea to explicitly be calling the beginning of the day instead of relying on a ruby quirk.  I'm  :ok_hand:  with it!

**Comment by mjgiarlo** [comment]
:clap:

**Pull request merged**
