### PR TITLE
Remove deprecation warnings

### PR DESCRIPTION
**Pull request by awead**
This preps Sufia for Blacklight 6.0 and removes deprecation warnings. Note, this PR depends on updates in projecthydra-labs/hydra-collections#74 and projectblacklight/blacklight_advanced_search#35 and shouldn't be merged until those are addressed and new gems have been released.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:clap: :+1: waiting on HC and BAS merges and releases.

**Comment by jcoyne** [comment]
Looks good. (pending dependency releases)

**Comment by awead** [comment]
New versions of hydra-collections and blacklight_advanced_search are out, so this is ready for a merge.

**Comment by jcoyne** [comment]
@awead shouldn't you pin to the correct versions of the gems?

**Comment by awead** [comment]
@jcoyne dunno. They're both patch releases. For example, currently:
```
'blacklight_advanced_search', '~> 5.1'
```
which we could modify to:
```
'blacklight_advanced_search', '>= 5.1.4, ~> 5.1'
```
Or do want to pin specifically to any 5.1.x release?

**Comment by jcoyne** [comment]
@awead yes, I think we ought to do that. This won't work with 5.1.0

**Comment by awead** [comment]
@jcoyne ok. Updated the dependencies and squashed a bit.

**Pull request merged**
