### PR TITLE
Switch to using an isolated namespace

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
This will break any application that has overridden views (they're now have `sufia/` in their path), so we may want to consider this for Sufia 8

**Comment by mjgiarlo** [comment]
@jcoyne Agreed. I'm not ready to push Sufia 8 yet, so let's keep the branch around for when we're ready to start working on 8.0 (after we have a tested upgrade/migration path from 6 to 7 and have finished some feature work). Thanks!

**Comment by cbeer** [comment]
If it's just overriding views, we ought to be able to add the current location to the lookup path.

**Comment by jcoyne** [comment]
Did this in Hyrax

**Pull request closed without merging**
