### PR TITLE
Remove any_instance_of in ingest_local_file_service_spec

### PR DESCRIPTION
**Pull request by grosscol**
refs #1617

Current practices guidelines for rspec call out `allow_any_instance_of` as bad form.  Replacing use with `object_double` and mocked methods instead.

The spec here only needs a single double of the FileSet instance as it can be reused between expectations.  The fileset is created as a recipient of the ingested file content, and the work of actually adding the content is done in a separate class.

Changes proposed in this pull request:
*  remove uses `allow_any_instance_of` from ingest_local_file_service_spec.rb

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by jcoyne** [comment]
Please hold off on merging this until the new file upload PR goes in (probably later today). There will be merge conflicts.

**Comment by mjgiarlo** [comment]
@jcoyne OK. ETA?

**Comment by mjgiarlo** [comment]
@grosscol Are you :cool: revisiting this (and rebasing + dealing with a few conflicts) once @jcoyne has had his PR merged?

**Comment by grosscol** [comment]
Yeah.  I'd be happy to.

**Comment by atz** [comment]
Can we link that PR here for visibility?

**Pull request merged**
