### PR TITLE
Adds CSS two column for collection show to match file show

### PR DESCRIPTION
**Pull request by mtribone**
We go from this:

screen shot 2015-02-25 at 11 15 38 am

To this:

screen shot 2015-02-27 at 9 18 28 am

### CODE REVIEW

**Comment by awead** [comment]
@mtribone my only beef with this is that the "Rights:" label is at the bottom of the first column and the content is at the top of the second. Is there a way to ensure the columns only break at labels, so the the label is always directly adjacent to the content?

**Comment by jcoyne** [comment]
@awead that's the joy of definition lists.

**Comment by mtribone** [comment]
@awead I had this conversation with @cam156 and perhaps saving that fix for another ticket. @jcoyne it's the CSS that breaks the dt and dd apart. The code is fluid enough to "evenly" distribute content into two columns, but breaks where it sees fit. I could add coulmn-height to see if there is an improvement, but I can't control the amount of user content. Or we'd have to break out all of the metadata individually and manually put them into Bootstrap columns. Thoughts?

**Comment by awead** [comment]
@mtribone I'm good with leaving this as is, or putting in another ticket to address this later -- if that's even possible. I was thinking:
```
<div class="dont-break-here">
  <dt>
  <dd>
</div>
```
Don't know...

**Comment by jcoyne** [comment]
@mtribone have you considered `break-before: avoid` on the `<dd>`

**Comment by mtribone** [comment]
@awead @jcoyne :clap:  Nice. I'll give them both a shot.

**Comment by jcoyne** [comment]
@awead you can't stick `div` in a `dl` http://www.w3.org/TR/html5/grouping-content.html#the-dl-element

**Comment by mtribone** [comment]
I also wonder if it is because there is an empty anchor element that is the first line. https://github.com/projecthydra/sufia/issues/939

**Comment by awead** [comment]
@jcoyne then a class on `dt` that disallows breaking might work.

**Comment by jcoyne** [comment]
@cam156 why is this `In Progress`? Is there any reason we can't merge it now?

**Comment by mtribone** [comment]
We can push the button and then work on 939 to help alleviate the issue. It doesn't happen on the file show page and I suspect it is because of the empty anchor.

**Comment by mjgiarlo** [comment]
@jcoyne waffle.io did that.

**Comment by jcoyne** [comment]
@mjgiarlo So what's the implication of that? Does that mean "do not merge because I'm working on it"?

**Comment by mjgiarlo** [comment]
I haven't touched waffle.io yet, so I'd defer to Carolyn.  Hey, @cam156?

**Comment by cam156** [comment]
@jcoyne @mjgiarlo No the implication is that someone assigned them self.  I'll see what I can do to change waffle so it does not add labels...

**Comment by mjgiarlo** [comment]
:ok: :+1:

**Pull request merged**
