### PR TITLE
Add optimistic locking to works

### LINKED ISSUE #3046: Files not added to a work when work is edited during background processing
This bug affects 7.2 and 7.3.

### Descriptive summary

If you upload a number of files to a work, then edit it and save while those files are still being processed in the background, they do not get successfully added to the work.

### Expected behavior

Background jobs and foreground jobs shouldn't mess with one another. Or, if they do, the UI shouldn't allow you to do things that will mess up your work.

### Actual behavior

Using the edit form appears to delete from the work any file added between the time the form loads and the time it saves.

### Steps to reproduce the behavior

1. Generate .internal_test_app
1. add `gem 'sidekiq'` to .internal_test_app/Gemfile; `bundle install`
1. add sidekiq routes to .internal_test_app/config/routes.rb ```require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'```
1. add `    config.active_job.queue_adapter = :sidekiq` to .internal_test_app/config/application.rb
1. run solr, fcrepo, rails server
1. in another terminal run sidekiq with `bundle exec sidekiq -q default -q ingest -q event`
1. in the browser, create a new work. upload a bunch of files to give yourself time; probably 15 is enough.
1. After you save, reload the work to see the first couple of files on the items list. click 'edit' before too many more files load.
1. make some metadata change (not sure if this is required, probably isn't) and click save (that part is required). Don't go too fast.
1. you can watch the sidekiq dashboard to see the jobs finish up.
1. reload the work to see that not all your files were added.

### PR DESCRIPTION
**Pull request by jcoyne**
Using the new optimistic lock in CurationConcerns
Fixes #3046

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@hackmastera You're seeing "Your files are being processed" on the edit form? I can't say I've ever seen a flash message rendered in that view. How to reproduce?

**Comment by jcoyne** [comment]
@hackmastera I've added the message to the form.  I'm not sure how you could be seeing "your files are being processed" if it's not saving the form.  That is only shown when the save is successful.

screen shot 2017-02-08 at 4 08 26 pm

**Comment by hackmastera** [comment]
Looks like @jcoyne's latest push fixed it for me in the simplest case. Going to run through the steps in #3046 now with sidekiq and everything.

**Comment by hackmastera** [comment]
I'm seeing the error in the more complicated case, as well. But I also see the processing notice. @mjgiarlo @jcoyne what do y'all think of this 
screen shot 2017-02-09 at 10 21 37 am

**Comment by hackmastera** [comment]
My last concern is that the user experience is rather befuddling. The error message is factual but gives no advice or context. The form reloads completely and any edits the user was trying to make are lost. Plus there's no way for the user to tell whether / when it's safe to try again.

Much of this is unavoidable as a practical matter for us, but let me take a stab at a new error message:

Your changes could not be saved because another user (or background job) updated this #{model} after you began editing. Please make sure all file attachments have completed successfully and try again. This form has refreshed with the most recent saved copy of the #{model}.

**Comment by jcoyne** [comment]
New error messages added in https://github.com/projecthydra/curation_concerns/pull/1149

**Comment by jcoyne** [comment]
New error messages added in https://github.com/projecthydra/curation_concerns/pull/1149

**Comment by hackmastera** [comment]
Okay I tried some stuff just on master and that notification appears to just stick around / follow me for some reason. unrelated to this PR.

**Pull request merged**
