### PR TITLE
Remove catch-all error routing from engine routes; fixes #1906

### LINKED ISSUE #1906: catch-all routing for 404 should be appended in generator, not in the engine
### Descriptive summary

Sufia 7 brings down from Sufia 6 this catch all route for 404s that requires the Sufia engine to be last in the application routes. This is annoying when you start running other generators in your app, and makes for surprising behavior changes because it is only added in non-dev, non-test environments. So your app will work until it's deployed, when suddenly things 404 mysteriously.

### Expected behavior

The generator appends the catch all route to the application routes instead of including them in the engine.

### Actual behavior

It includes them in the engine.

### Steps to reproduce the behavior

1. Generate a Sufia app, then localize it with some new routes.

### Related work

None so far.

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by jcoyne** [comment]
Does this need to be sufia 8 or can it be 7.1?

**Comment by mjgiarlo** [comment]
I hope we can make it 7.2 if semver can allow it.

**Comment by cbeer** [comment]
I think 7.x is fine; this is just swapping one error implementation (sufia's) with another (rails') with essentially the same end-user behavior.

**Comment by mjgiarlo** [comment]
I'll buy that for a dollar.

**Comment by jcoyne** [comment]
Curiously the Rails 4.2 build completely fell apart.

**Comment by jcoyne** [comment]
Additionally remove `https://github.com/projecthydra/sufia/blob/master/app/views/errors/404.html.erb`

**Comment by jcoyne** [comment]
And update the generator: https://github.com/projecthydra/sufia/blob/master/lib/generators/sufia/install_generator.rb#L108-L109

**Pull request merged**
